FIREBASE_DB_URL = "https://green-shelf-63225-default-rtdb.firebaseio.com/"


EMAIL_SENDER = "amitvjadhav@coep.sveri.ac.in"
EMAIL_PASSWORD = "wshq ilxn psah cugl"
EMAIL_RECEIVER = "pratikshabshinde@coep.sveri.ac.in"